### PR TITLE
HS-1467: Add users.properties

### PR DESCRIPTION
**Pull request by cgorantla**
## Description
This will set default users.properties in Karaf.
Will facilitate easy acess to karaf shell.
Users.properties content copied from Classic.

## Jira link(s)
- https://issues.opennms.org/browse/HS-1467

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

### CODE REVIEW

**Review by splatch — APPROVED** [review]
:+1:  If we make this, then I think its worth to remove `karafUsers` from minion config map we deploy into kubernetes.

**Review by j-white — APPROVED** [review]
👍

**Review by artnaseef — COMMENTED** [review]
Are we not concerned about the security implications of backing in admin/admin into the base assembly that is used by all our deployments (including production)?

I would feel a lot better if it were somehow kept out of that base image and used in a dev-only image.

**Comment by cgorantla** [comment]
> Are we not concerned about the security implications of backing in admin/admin into the base assembly that is used by all our deployments (including production)?
> 
> I would feel a lot better if it were somehow kept out of that base image and used in a dev-only image.

Since this is a configurable item, we can always override the defaults.

**Pull request merged**
