### PR TITLE
HS-836: Use new Monitor Type AZURE in Monitor and Collector

### PR DESCRIPTION
**Pull request by thomasbigger584**
## Description
REQUEST:

```
GET /prometheus/api/v1/query?query=ifOutOctets{instance="127.0.0.2", monitor="AZURE", node_id="2"}[1000s]
X-Scope-OrgID: opennms-prime
```

RESPONSE:

```
{
    "status": "success",
    "data": {
        "resultType": "matrix",
        "result": [
            {
                "metric": {
                    "__name__": "ifOutOctets",
                    "instance": "127.0.0.2",
                    "location": "Default",
                    "monitor": "AZURE",
                    "node_id": "2",
                    "system_id": "opennms-minion-5885b9df75-hf5kn"
                },
                "values": [
                    [
                        1674221552.342,
                        "123605"
                    ]
                ]
            }
        ]
    }
}
```

## Jira link(s)
- https://issues.opennms.org/browse/HS-836

## Checklist
* [x] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [x] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

### CODE REVIEW

**Review by james8hut — APPROVED** [review]
LGTM

**Review by yangli2014 — COMMENTED** [review]
How can we test it?

**Review by cgorantla — COMMENTED** [review]
Looks good to me.

Are we still using same SNMP metrics names,
Will that be handled in another PR ?

**Comment by thomasbigger584** [comment]
> Are we still using same SNMP metrics names, Will that be handled in another PR ?

Have we decided what the common metric names are?

**Comment by cgorantla** [comment]
> > Are we still using same SNMP metrics names, Will that be handled in another PR ?
> 
> Have we decided what the common metric names are?

We might use the same metrics as Azure. Anyways we can handle this when we work on normalization of SNMP/Azure metrics.

**Comment by thomasbigger584** [comment]
> > > Are we still using same SNMP metrics names, Will that be handled in another PR ?
> > 
> > 
> > Have we decided what the common metric names are?
> 
> We might use the same metrics as Azure. Anyways we can handle this when we work on normalization of SNMP/Azure metrics.

Sure, will make the change in this PR. 

Preferably would like this PR not to be merged until after the Azure demo. This PR on its own will make the graphs stop working.

**Review by cgorantla — APPROVED** [review]

**Pull request merged**
