### PR TITLE
HS-1156 - BFF:  Integrate Alerts gRPC API

### PR DESCRIPTION
**Pull request by BenjaminJ**
## Description
Integrate Alerts gRPC API into BFF.

## Jira link(s)
- https://issues.opennms.org/browse/HS-1156

## Flagged for review
Not sure about value grpc.url.alerts: localhost:16065

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.
* [ ] Notify devops of changes to the Charts

### CODE REVIEW

**Review by geraldhumphries — APPROVED** [review]

**Comment by thomasbigger584** [comment]
looks good to me, looks like theres a minor conflict

**Review by cgorantla — APPROVED** [review]
LGTM!

**Review by yangli2014 — COMMENTED** [review]
I got the following error when I tried the new GraphQL endpoints
```
[reactor-http-nio-4] WARN notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler - Exception while fetching data (/findAllAlerts) : UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at org.opennms.horizon.alerts.proto.AlertServiceGrpc$AlertServiceBlockingStub.listAlerts(AlertServiceGrpc.java:422)
	at org.opennms.horizon.server.service.grpc.AlertsClient.listAlerts(AlertsClient.java:65)
	at org.opennms.horizon.server.service.GrpcAlertService.findAllAlerts(GrpcAlertService.java:58)
......
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:32065
Caused by: java.net.ConnectException: Connection refused
```
I believe the rest-server application.yml or environment variable is not configured correctly.

**Review by yangli2014 — APPROVED** [review]
LGTM

**Pull request merged**
